"""rename uz fields to en in category and product

Revision ID: 4d0df0de78f5
Revises: acc45bac5f77
Create Date: 2026-08-21 14:16:28.338584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0df0de78f5'
down_revision: Union[str, None] = 'acc45bac5f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.drop_column('categories', 'name_uz')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_uz', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('categories', 'name_en')
    # ### end Alembic commands ###
