"""rename uz fields to en in product

Revision ID: 6f82b657a756
Revises: 4d0df0de78f5
Create Date: 2026-08-21 14:18:49.372962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f82b657a756'
down_revision: Union[str, None] = '4d0df0de78f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('description_en', sa.Text(), nullable=True))
    op.drop_column('products', 'name_uz')
    op.drop_column('products', 'description_uz')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description_uz', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('name_uz', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_en')
    # ### end Alembic commands ###
